services:
  - type: web
    name: dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn dashboard_platform.wsgi --bind 0.0.0.0:$PORT
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "*.onrender.com"
      - key: PYTHON_VERSION
        value: "3.11"
      - key: DATABASE_URL
        fromService:
          name: postgres
          property: connectionString
    autoDeploy: true

  - type: pserv
    name: postgres
    plan: free
    ipAllowList: []

  - type: cron
    name: health-check
    schedule: "*/5 * * * *"
    command: "curl -s https://datavista-dashboard.onrender.com/health/"
    region: oregon

  - type: job
    name: migrate
    env: python
    command: pip install -r requirements.txt && python manage.py migrate --run-syncdb
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: DATABASE_URL
        fromService:
          name: postgres
          property: connectionString
