# Generated by Django 5.2.5 on 2025-09-02 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_subscriptionplan_usersubscription_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'ordering': ['price_usd']},
        ),
        migrations.RenameField(
            model_name='subscriptionplan',
            old_name='price',
            new_name='price_usd',
        ),
        migrations.RenameField(
            model_name='subscriptionplan',
            old_name='yearly_price',
            new_name='yearly_price_inr',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='price_inr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='yearly_price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
